### ISSUE TITLE
Delete the Guest Wallet

### ISSUE THREAD

**Issue by LtSnakePlissken** [real-hansolo/ralph-the-moose#11]
### Description

Unless we can figure out how to switch network, but sounds like too much work, so delete that sh*t

**Comment by LtSnakePlissken** [comment]
To remove the guest wallet feature completely, you can follow these steps:

Update the ConnectWallet component in your app to remove the option for guests to continue as guests.
Remove any references or links to the guest wallet feature in your app's UI.
Make sure to update your app's theme and UI to reflect the removal of the guest wallet feature.
Test your app thoroughly to ensure that the guest wallet feature is no longer accessible.

**Comment by real-hansolo** [comment]
Done ;)
